#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_DIR="${COMAI_INSTALL_DIR:-$HOME/localcomai}"
BIN_DIR="${HOME}/.local/bin"
SYSTEMD_USER_DIR="${HOME}/.config/systemd/user"
REQUIRED_COMMANDS=(bash curl jq find sort head sed awk grep wc tr readlink systemctl)
OPTIONAL_COMMANDS=(file numfmt)

missing_commands() {
  local cmd
  MISSING_COMMANDS=()
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || MISSING_COMMANDS+=("$cmd")
  done
}

package_for_command() {
  case "$1" in
    bash) printf 'bash' ;;
    curl) printf 'curl' ;;
    jq) printf 'jq' ;;
    find) printf 'findutils' ;;
    sort|head|wc|tr|readlink|numfmt) printf 'coreutils' ;;
    sed) printf 'sed' ;;
    awk) printf 'gawk' ;;
    grep) printf 'grep' ;;
    file) printf 'file' ;;
    systemctl) printf 'systemd' ;;
    *) printf '%s' "$1" ;;
  esac
}

install_packages_for_missing_commands() {
  local packages=()
  local cmd package

  for cmd in "${MISSING_COMMANDS[@]}"; do
    package="$(package_for_command "$cmd")"
    [[ " ${packages[*]} " == *" $package "* ]] || packages+=("$package")
  done

  [[ "${#packages[@]}" -gt 0 ]] || return 0

  if command -v apt-get >/dev/null 2>&1; then
    printf 'Installing required packages: %s\n' "${packages[*]}"
    sudo apt-get update
    sudo apt-get install -y "${packages[@]}"
  elif command -v dnf >/dev/null 2>&1; then
    printf 'Installing required packages: %s\n' "${packages[*]}"
    sudo dnf install -y "${packages[@]}"
  elif command -v pacman >/dev/null 2>&1; then
    printf 'Installing required packages: %s\n' "${packages[*]}"
    sudo pacman -S --needed "${packages[@]}"
  else
    printf 'Missing required commands: %s\n' "${MISSING_COMMANDS[*]}" >&2
    printf 'Install them with your package manager, then rerun this installer.\n' >&2
    return 1
  fi
}

install_command_wrapper() {
  local target="$1"
  local command_path="$2"

  if [[ -L "$command_path" ]]; then
    rm -f "$command_path"
  elif [[ -e "$command_path" ]]; then
    if ! grep -q 'Generated by ComAI installer' "$command_path" 2>/dev/null; then
      printf 'Cannot install %s: path exists and is not managed by ComAI.\n' "$command_path" >&2
      return 1
    fi
  fi

  if [[ ! -x "$target" ]]; then
    printf 'Cannot install %s: target is not executable: %s\n' "$command_path" "$target" >&2
    return 1
  fi

  cat > "$command_path" <<EOF
#!/usr/bin/env bash
# Generated by ComAI installer. Do not edit by hand.
exec "$target" "\$@"
EOF
  chmod +x "$command_path"
}

path_has_bin_dir() {
  case ":$PATH:" in
    *":$BIN_DIR:"*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

shell_config_file() {
  case "${SHELL:-}" in
    */zsh)
      printf '%s\n' "$HOME/.zshrc"
      ;;
    */fish)
      printf '%s\n' "$HOME/.config/fish/config.fish"
      ;;
    *)
      printf '%s\n' "$HOME/.bashrc"
      ;;
  esac
}

ensure_path_config() {
  local config_file line fish_line

  if path_has_bin_dir; then
    PATH_NOTE="PATH already contains $BIN_DIR."
    return 0
  fi

  config_file="$(shell_config_file)"
  mkdir -p "$(dirname "$config_file")"

  if [[ "${SHELL:-}" == */fish ]]; then
    fish_line="fish_add_path -p $BIN_DIR"
    if ! grep -Fqx "$fish_line" "$config_file" 2>/dev/null; then
      printf '\n# Added by ComAI installer\n%s\n' "$fish_line" >> "$config_file"
    fi
  else
    line='export PATH="$HOME/.local/bin:$PATH"'
    if ! grep -Fqx "$line" "$config_file" 2>/dev/null; then
      printf '\n# Added by ComAI installer\n%s\n' "$line" >> "$config_file"
    fi
  fi

  PATH_NOTE="Added $BIN_DIR to $config_file. Restart your shell or run: export PATH=\"\$HOME/.local/bin:\$PATH\""
}

missing_commands "${REQUIRED_COMMANDS[@]}"
install_packages_for_missing_commands

missing_commands "${OPTIONAL_COMMANDS[@]}"
if [[ "${#MISSING_COMMANDS[@]}" -gt 0 ]]; then
  printf 'Optional commands not found: %s\n' "${MISSING_COMMANDS[*]}"
  printf 'ComAI still works, but file type detection and human-readable sizes may be less polished.\n'
fi

mkdir -p "$INSTALL_DIR" "$BIN_DIR" "$SYSTEMD_USER_DIR"

rm -rf "$INSTALL_DIR/bin" "$INSTALL_DIR/lib" "$INSTALL_DIR/config" "$INSTALL_DIR/scripts"
mkdir -p "$INSTALL_DIR/bin" "$INSTALL_DIR/lib" "$INSTALL_DIR/config" "$INSTALL_DIR/scripts"

cp -R "$ROOT_DIR/bin/." "$INSTALL_DIR/bin/"
cp -R "$ROOT_DIR/lib/." "$INSTALL_DIR/lib/"
cp -R "$ROOT_DIR/config/." "$INSTALL_DIR/config/"
cp "$ROOT_DIR/scripts/comai-localai-service.sh" "$INSTALL_DIR/scripts/"
cp "$ROOT_DIR/scripts/uninstall.sh" "$INSTALL_DIR/scripts/"

chmod +x "$INSTALL_DIR/bin/comai" "$INSTALL_DIR/scripts/comai-localai-service.sh" "$INSTALL_DIR/scripts/uninstall.sh"

install_command_wrapper "$INSTALL_DIR/bin/comai" "$BIN_DIR/comai"
install_command_wrapper "$INSTALL_DIR/bin/comai" "$BIN_DIR/comi"

cat > "$SYSTEMD_USER_DIR/comai-localai.service" <<EOF
[Unit]
Description=ComAI local AI server
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$INSTALL_DIR/scripts/comai-localai-service.sh start
ExecStop=$INSTALL_DIR/scripts/comai-localai-service.sh stop

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now comai-localai.service
ensure_path_config

cat <<EOF
Installed:
  $INSTALL_DIR
  $BIN_DIR/comai
  $BIN_DIR/comi
  $SYSTEMD_USER_DIR/comai-localai.service
  $INSTALL_DIR/config/comai.yaml
  $INSTALL_DIR/lib/comai/

Service:
  comai-localai.service enabled and started

PATH:
  $PATH_NOTE

Try:
  comai hi
  comai what is /etc in linux?
EOF
